version: '3.8'
services:
  whisper-api:
    build: ./whisper-api
    ports:
      - "5000:5000"
  rag-backend:
    build: ./rag-backend
    ports:
      - "6000:6000"
    environment:
      - OPENAI_API_KEY=your-openai-key
      - PG_URI=postgresql://postgres:postgres@host.docker.internal:5432/genai
